services:
  web:
    build: .
    ports:
      - "8000:8000"
 
    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn personalblog.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media

    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
      